import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LoginLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (session) redirect("/logout");

  return (
    <div
      className={`${inter.className} flex flex-col w-full max-w-full min-h-[100vh] `}
    >
      {children}
    </div>
  );
}
