export const testQuote =
  "A classroom is a place where young minds embark on a journey of discovery, guided by the wisdom of teachers and fueled by the curiosity of students.";

export const randomAssignmentList = [
  {
    className: "Class A",
    teacher: "John Fernando",
    latestAssignemntDate: "2023-04-05",
    assignmentsCompleted: 3,
    assignemntsLeft: 4,
    latestAssignmentDue: "2 days left",
  },
  {
    className: "Class B",
    teacher: "Alice Smith",
    latestAssignemntDate: "2023-03-15",
    assignmentsCompleted: 7,
    assignemntsLeft: 3,
    latestAssignmentDue: "5 days left",
  },
  {
    className: "Class C",
    teacher: "Bob Johnson",
    latestAssignemntDate: "2023-02-22",
    assignmentsCompleted: 5,
    assignemntsLeft: 2,
    latestAssignmentDue: "3 days left",
  },
  {
    className: "Class A",
    teacher: "Emily Brown",
    latestAssignemntDate: "2023-04-01",
    assignmentsCompleted: 1,
    assignemntsLeft: 6,
    latestAssignmentDue: "4 days left",
  },
  {
    className: "Class D",
    teacher: "John Fernando",
    latestAssignemntDate: "2023-03-10",
    assignmentsCompleted: 4,
    assignemntsLeft: 1,
    latestAssignmentDue: "1 day left",
  },
  // {
  //   className: "Class B",
  //   teacher: "Alice Smith",
  //   latestAssignemntDate: "2023-03-25",
  //   assignmentsCompleted: 2,
  //   assignemntsLeft: 5,
  //   latestAssignmentDue: "6 days left",
  // },
  // {
  //   className: "Class C",
  //   teacher: "Bob Johnson",
  //   latestAssignemntDate: "2023-04-02",
  //   assignmentsCompleted: 6,
  //   assignemntsLeft: 0,
  //   latestAssignmentDue: "Due Today",
  // },
  // {
  //   className: "Class A",
  //   teacher: "Emily Brown",
  //   latestAssignemntDate: "2023-03-17",
  //   assignmentsCompleted: 8,
  //   assignemntsLeft: 2,
  //   latestAssignmentDue: "2 days left",
  // },
  // {
  //   className: "Class D",
  //   teacher: "John Fernando",
  //   latestAssignemntDate: "2023-02-28",
  //   assignmentsCompleted: 3,
  //   assignemntsLeft: 4,
  //   latestAssignmentDue: "4 days left",
  // },
  // {
  //   className: "Class B",
  //   teacher: "Alice Smith",
  //   latestAssignemntDate: "2023-03-08",
  //   assignmentsCompleted: 2,
  //   assignemntsLeft: 3,
  //   latestAssignmentDue: "3 days left",
  // },
];
