export const testQuote =
  "A classroom is a place where young minds embark on a journey of discovery, guided by the wisdom of teachers and fueled by the curiosity of students.";

export const assignmentDetils = [
  {
    assignmentName: "Maths area assignment",
    class: "Maths grade 10",
    teacher: "John Fernando",
    dueDate: "2023-10-05",
    status: "Submitted",
  },
  {
    assignmentName: "English Essay",
    class: "English grade 9",
    teacher: "Emily Smith",
    dueDate: "2023-09-25",
    status: "Not Submitted",
  },
  {
    assignmentName: "Science Experiment",
    class: "Science grade 8",
    teacher: "Michael Johnson",
    dueDate: "2023-09-30",
    status: "Submitted",
  },
  {
    assignmentName: "History Research Paper",
    class: "History grade 11",
    teacher: "Sarah Adams",
    dueDate: "2023-10-10",
    status: "Submitted",
  },
  {
    assignmentName: "Computer Science Project",
    class: "Computer Science grade 12",
    teacher: "David Lee",
    dueDate: "2023-10-03",
    status: "Not Submitted",
  },
];

export const randomAssignmentList = [
  {
    className: "Class A",
    teacher: "John Fernando",
    latestAssignemntDate: "2023-04-05",
    assignmentsCompleted: 3,
    assignemntsLeft: 4,
    latestAssignmentDue: "2 days left",
  },
  {
    className: "Class B",
    teacher: "Alice Smith",
    latestAssignemntDate: "2023-03-15",
    assignmentsCompleted: 7,
    assignemntsLeft: 3,
    latestAssignmentDue: "5 days left",
  },
  {
    className: "Class C",
    teacher: "Bob Johnson",
    latestAssignemntDate: "2023-02-22",
    assignmentsCompleted: 5,
    assignemntsLeft: 2,
    latestAssignmentDue: "3 days left",
  },
  {
    className: "Class A",
    teacher: "Emily Brown",
    latestAssignemntDate: "2023-04-01",
    assignmentsCompleted: 1,
    assignemntsLeft: 6,
    latestAssignmentDue: "4 days left",
  },
  {
    className: "Class D",
    teacher: "John Fernando",
    latestAssignemntDate: "2023-03-10",
    assignmentsCompleted: 4,
    assignemntsLeft: 1,
    latestAssignmentDue: "1 day left",
  },
  // {
  //   className: "Class B",
  //   teacher: "Alice Smith",
  //   latestAssignemntDate: "2023-03-25",
  //   assignmentsCompleted: 2,
  //   assignemntsLeft: 5,
  //   latestAssignmentDue: "6 days left",
  // },
  // {
  //   className: "Class C",
  //   teacher: "Bob Johnson",
  //   latestAssignemntDate: "2023-04-02",
  //   assignmentsCompleted: 6,
  //   assignemntsLeft: 0,
  //   latestAssignmentDue: "Due Today",
  // },
  // {
  //   className: "Class A",
  //   teacher: "Emily Brown",
  //   latestAssignemntDate: "2023-03-17",
  //   assignmentsCompleted: 8,
  //   assignemntsLeft: 2,
  //   latestAssignmentDue: "2 days left",
  // },
  // {
  //   className: "Class D",
  //   teacher: "John Fernando",
  //   latestAssignemntDate: "2023-02-28",
  //   assignmentsCompleted: 3,
  //   assignemntsLeft: 4,
  //   latestAssignmentDue: "4 days left",
  // },
  // {
  //   className: "Class B",
  //   teacher: "Alice Smith",
  //   latestAssignemntDate: "2023-03-08",
  //   assignmentsCompleted: 2,
  //   assignemntsLeft: 3,
  //   latestAssignmentDue: "3 days left",
  // },
];

export const randomQuizesList = [
  {
    name: "Quiz one",
    class: "Class A",
    status: "Marked",
    Marks: 45,
  },
  {
    name: "Math Quiz",
    class: "Class B",
    status: "Not Marked",
    Marks: 30,
  },
  {
    name: "Science Test",
    class: "Class C",
    status: "Marked",
    Marks: 50,
  },
  {
    name: "History Quiz",
    class: "Class A",
    status: "Marked",
    Marks: 38,
  },
  {
    name: "English Quiz",
    class: "Class B",
    status: "Not Marked",
    Marks: 28,
  },
  // {
  //   name: "Geography Test",
  //   class: "Class C",
  //   status: "Marked",
  //   Marks: 49,
  // },
  // {
  //   name: "Physics Quiz",
  //   class: "Class A",
  //   status: "Marked",
  //   Marks: 42,
  // },
  // {
  //   name: "Chemistry Test",
  //   class: "Class B",
  //   status: "Not Marked",
  //   Marks: 32,
  // },
  // {
  //   name: "Biology Quiz",
  //   class: "Class C",
  //   status: "Marked",
  //   Marks: 47,
  // },
  // {
  //   name: "Literature Quiz",
  //   class: "Class A",
  //   status: "Marked",
  //   Marks: 39,
  // },
];

export const classRooms = [
  {
    className: "Maths Class",
    grade: "Grade 10",
    subject: "Maths",
    students: 23,
    latestDueAssignment: "2023/08/12",
    year: "2023",
  },
  {
    className: "Science Class",
    grade: "Grade 9",
    subject: "Science",
    students: 18,
    latestDueAssignment: "2023/08/15",
    year: "2023",
  },
  {
    className: "History Class",
    grade: "Grade 11",
    subject: "History",
    students: 30,
    latestDueAssignment: "2023/08/10",
    year: "2023",
  },
  {
    className: "English Class",
    grade: "Grade 12",
    subject: "English",
    students: 25,
    latestDueAssignment: "2023/08/20",
    year: "2023",
  },
  {
    className: "Physics Class",
    grade: "Grade 11",
    subject: "Physics",
    students: 22,
    latestDueAssignment: "2023/08/14",
    year: "2023",
  },
  {
    className: "Computer Science Class",
    grade: "Grade 10",
    subject: "Computer Science",
    students: 28,
    latestDueAssignment: "2023/08/18",
    year: "2023",
  },
  {
    className: "Art Class",
    grade: "Grade 9",
    subject: "Art",
    students: 15,
    latestDueAssignment: "2023/08/16",
    year: "2023",
  },
  {
    className: "Physical Education Class",
    grade: "Grade 12",
    subject: "Physical Education",
    students: 20,
    latestDueAssignment: "2023/08/22",
    year: "2023",
  },
  {
    className: "Biology Class",
    grade: "Grade 10",
    subject: "Biology",
    students: 27,
    latestDueAssignment: "2023/08/13",
    year: "2023",
  },
  {
    className: "Music Class",
    grade: "Grade 9",
    subject: "Music",
    students: 12,
    latestDueAssignment: "2023/08/19",
    year: "2023",
  },
];
